# Generated by Django 3.1.2 on 2020-11-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=5)),
                ('company_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_current', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('predicted_price_open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_price_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_price_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_price_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.stocks')),
            ],
        ),
    ]
